### PR TITLE
IITQ 7

### PR DESCRIPTION
**Pull request by jeremie-gauthier**
I've set various things for the base frontend setup (tests, state manager...)

I've implemented the Navbar as I understood it from [IITQ-7](https://42hyper.atlassian.net/browse/IITQ-7)

**HINT:** Don't forget to run `npm install` after having checkout on this branch.
And ensure that the tests coverage is correct by running `npm run coverage`.

### CODE REVIEW

**Review by caro-rokah — CHANGES_REQUESTED** [review]
- [X] Name of the languages should always be in the right language : ex : Français, English
- [x] the hover effect on the floaters for the account and the language should be a darker grey background
- [x] the search input should be open on click on the icon (no more "search"), it should open an input space  with a place holder saying "Search a movie".
- [x] the name of the page we're on should be a little bigger OR the name of the page should be underlined at the bottom of the navbar
- [x] mobile view to be adapted from the figma

EDIT: formatting

**Comment by jeremie-gauthier** [comment]
Hey @caro-rokah !
Please check out the new changes :rocket:

**Review by caro-rokah — APPROVED** [review]
It's beautiful !

**Comment by jeremie-gauthier** [comment]
@all-contributors please add @caro-rokah for design

**Pull request merged**
